create database sales;
use sales;


show tables;


select * from orders;
select * from customers;
select * from products;

select customerid ,count(*) as number_of_orders from orders group by customerid;
select * from orders inner join customers;


#total orders per date
select OrderDate,count(orderID) from orders group by orderdate;


#Total orders
select count(*) as total_orders from orders;


# total sales
select sum((P.PRICE*O.QUANTITY)-((P.PRICE*O.QUANTITY)*O.DISCOUNT/100)) AS TOTAL_SALES FROM PRODUCTS P INNER JOIN ORDERS O ON P.PRODUCTID=O.PRODUCTID;


#SALES BY REGION
SELECT C.REGION,sum((P.PRICE*O.QUANTITY)-((P.PRICE*O.QUANTITY)*O.DISCOUNT/100))  AS SALES
FROM ORDERS O JOIN CUSTOMERS C ON C.CUSTOMERID=O.CUSTOMERID
JOIN PRODUCTS P ON P.PRODUCTID=O.PRODUCTID
GROUP BY C.REGION;

#MONTHLY SALES
SELECT  MONTHNAME(O.ORDERDATE) AS MTH ,sum((P.PRICE*O.QUANTITY)-((P.PRICE*O.QUANTITY)*O.DISCOUNT/100)) AS MONTH_SALES
FROM ORDERS O JOIN PRODUCTS P
ON O.PRODUCTID=P.PRODUCTID
GROUP BY MTH;

#TOP 5 PRODCUTS BY SALES
SELECT P.PRODUCTID,sum((P.PRICE*O.QUANTITY)-((P.PRICE*O.QUANTITY)*O.DISCOUNT/100)) AS SALES
FROM ORDERS O JOIN PRODUCTS P
ON O.PRODUCTID=P.PRODUCTID 
GROUP BY P.PRODUCTID
ORDER BY SALES DESC
LIMIT 5;

#AVERAGE ORDER VALUE
SELECT AVG((P.PRICE*O.QUANTITY)-((P.PRICE*O.QUANTITY)*O.DISCOUNT/100)) AS AVG_VALUE FROM ORDERS O JOIN PRODUCTS P
ON O.PRODUCTID=P.PRODUCTID;

#SALES BY CATEGORY
SELECT P.CATEGORY,sum((P.PRICE*O.QUANTITY)-((P.PRICE*O.QUANTITY)*O.DISCOUNT/100)) AS SALES
FROM ORDERS O JOIN PRODUCTS P ON O.PRODUCTID=P.PRODUCTID
GROUP BY CATEGORY;

#ACTIVE CUSTOMERS BY REGION
SELECT REGION, COUNT(CUSTOMERID) FROM CUSTOMERS GROUP BY REGION;
SELECT C.REGION,COUNT(DISTINCT O.CUSTOMERID) FROM ORDERS O JOIN CUSTOMERS C 
ON C.CUSTOMERID=O.CUSTOMERID GROUP BY C.REGION;
